server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: novel-reading-app
  data:
    mongodb:
      uri: mongodb://localhost:27017/novel_reading_db_dev
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.miraimagiclab.novelreadingapp: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
