server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: novel-reading-app
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/novel_reading_db}
      auto-index-creation: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.miraimagiclab.novelreadingapp: INFO
    org.springframework.data.mongodb: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/novel-reading-app.log

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,https://yourdomain.com}
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
